In [2]:
import numpy as np
arr=np.array([2,3,34,7,57,7],dtype=np.int64)
arr

array([ 2,  3, 34,  7, 57,  7])

In [3]:
print(arr.size)
print(type(arr))
print(arr.shape)
print(arr.itemsize)
print(arr.ndim)

6
<class 'numpy.ndarray'>
(6,)
8
1


In [4]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [5]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [6]:
arr.itemsize

8

In [7]:
arr.reshape(3,2)

array([[ 2,  3],
       [34,  7],
       [57,  7]])

In [8]:
np.zeros((5,2),dtype=bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [9]:
np.ones(8,dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
np.random.rand(10)*100

array([48.54638113,  6.1488521 , 90.06771221, 61.6850547 , 80.32766146,
       11.71734552, 55.93767504, 80.71434303, 85.97991325, 38.27826096])

In [11]:
arr2=np.array((2,34,3,5,646,6))
arr2

array([  2,  34,   3,   5, 646,   6])

In [12]:
arr2[3:-2:-1]

array([], dtype=int64)

In [13]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3 + 10)   # [11 12 13 14 15] - Addition
print(arr3 - 2)    # [-1  0  1  2  3] - Subtraction
print(arr3 * 2)    # [ 2  4  6  8 10] - Multiplication
print(arr3 / 2)    # [0.5 1.  1.5 2.  2.5] - Division
print(arr3 // 2)   # [0 1 1 2 2] - Floor Division
print(arr3 % 2)    # [1 0 1 0 1] -remainder


[11 12 13 14 15]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]


In [14]:
arr4=np.array([4,56,78,23,9])
print(np.min(arr4))

4


In [15]:
arr2[arr2<10]

array([2, 3, 5, 6])

In [16]:
print(np.max(arr4))

78


In [17]:
arr5=np.array([34,85,86,87,88])
np.mean(arr5)

np.float64(76.0)

In [18]:
print(np.var(arr5))

442.0


In [19]:
print(np.std(arr5))

21.02379604162864


In [20]:
arr6 = np.array([5, 2, 8, 1, 3])
np.sort(arr6)  # [1 2 3 5 8]
arr7 = np.array([1, 2, 3])
arr7.astype(float)  # [1 2 3]


array([1., 2., 3.])

In [21]:
arr8 = np.array([10, 20, 30, 40, 50])
print(np.where(arr8 > 25) )   # (array([2, 3, 4]),) where() returns indices 
print(np.any(arr > 45)  )    # True
print(np.all(arr > 45) )      # True


(array([2, 3, 4]),)
True
False


In [22]:
arr9=np.array([[2,3,5,],[6,8,9],[0,77,23]])
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [23]:
arr9[1,1]

np.int64(8)

In [24]:
arr9[2,2]

np.int64(23)

In [25]:
arr9[1]

array([6, 8, 9])

In [26]:
arr9[2]

array([ 0, 77, 23])

In [27]:
arr9[:,1]

array([ 3,  8, 77])

In [28]:
a=[2,3,54,5,46]
print(a[:])

[2, 3, 54, 5, 46]


In [29]:
arr9[:,2]
print(arr9)

[[ 2  3  5]
 [ 6  8  9]
 [ 0 77 23]]


In [30]:
arr9[1:3,0:2]

array([[ 6,  8],
       [ 0, 77]])

In [31]:
arr9[:2,:2]

array([[2, 3],
       [6, 8]])

In [32]:
arr9[:,2]

array([ 5,  9, 23])

In [33]:
arr9[:,1]

array([ 3,  8, 77])

In [34]:
arr9[::2]

array([[ 2,  3,  5],
       [ 0, 77, 23]])

In [35]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [36]:
arr9[1:]

array([[ 6,  8,  9],
       [ 0, 77, 23]])

In [37]:
arr9[:2]

array([[2, 3, 5],
       [6, 8, 9]])

In [38]:
arr9[::2]

array([[ 2,  3,  5],
       [ 0, 77, 23]])

In [39]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [40]:
arr9[:,0]

array([2, 6, 0])

In [41]:
arr9[:,2]

array([ 5,  9, 23])

In [42]:
arr9[:,:2]

array([[ 2,  3],
       [ 6,  8],
       [ 0, 77]])

In [43]:
arr9[::2,::2]

array([[ 2,  5],
       [ 0, 23]])

In [44]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [45]:
arr9[[0,2]]

array([[ 2,  3,  5],
       [ 0, 77, 23]])

In [46]:
arr9[:2]

array([[2, 3, 5],
       [6, 8, 9]])

In [47]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [48]:
for i in arr9:
    for j in i:
         print(j)

2
3
5
6
8
9
0
77
23


In [49]:
for i in np.nditer(arr9):
    print(i)

2
3
5
6
8
9
0
77
23


In [50]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [51]:
arr9[::2,]

array([[ 2,  3,  5],
       [ 0, 77, 23]])

In [52]:
arr9[[0,2]]

array([[ 2,  3,  5],
       [ 0, 77, 23]])

In [53]:
arr9[[1,2]]

array([[ 6,  8,  9],
       [ 0, 77, 23]])

In [54]:
arr9[:,[0,1]]

array([[ 2,  3],
       [ 6,  8],
       [ 0, 77]])

In [55]:
arr9[:,[1]]

array([[ 3],
       [ 8],
       [77]])

In [56]:
arr9[:,1:2]

array([[ 3],
       [ 8],
       [77]])

In [57]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [58]:
arr9[[0,2],::2]

array([[ 2,  5],
       [ 0, 23]])

In [59]:
arr9[[1,2],::2]

array([[ 6,  9],
       [ 0, 23]])

In [60]:
arr9


array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [61]:
arr9[[0,1],::2]

array([[2, 5],
       [6, 9]])

In [62]:
arr9

array([[ 2,  3,  5],
       [ 6,  8,  9],
       [ 0, 77, 23]])

In [63]:
matrix1=[[2,4],
         [45,6]]
matrix2=[[12,3],
         [4,16]]
m1=np.array(matrix1)
m2=np.array(matrix2)
print(m1+m2)
print(m1-m2)

[[14  7]
 [49 22]]
[[-10   1]
 [ 41 -10]]


In [64]:
matrix3=[
    [2,4,6],
    [5,8,9],
    [0,9,1]]
matrix4=[
    [7,3,5],
    [4,8,9],
    [10,9,1]]
m3=np.array(matrix3)
m4=np.array(matrix4)
m3+m4

array([[ 9,  7, 11],
       [ 9, 16, 18],
       [10, 18,  2]])

In [65]:
m3-m4

array([[ -5,   1,   1],
       [  1,   0,   0],
       [-10,   0,   0]])

In [66]:
m3*m4

array([[14, 12, 30],
       [20, 64, 81],
       [ 0, 81,  1]])

In [67]:
matrix5=[[2,1],
         [4,4]]
matrix6=[[3,0],
         [-2,7]]
m5=np.array(matrix5)
m6=np.array(matrix6)
np.dot(m5,m6)

array([[ 4,  7],
       [ 4, 28]])

In [68]:
m7=np.array([[2,1],
            [4,7]])
m8=np.array([[3,4,8],
             [1,0,-2]])
np.dot(m7,m8)

array([[ 7,  8, 14],
       [19, 16, 18]])